### ISSUE TITLE
Still not usable

### ISSUE THREAD

**Issue by johnd0e** [dsdanielpark/Gemini-API#22]
1. `GeminiClient = Gemini(cookie_fp="cookies.json")`
   For this case instructions recommends [ExportThisCookies](https://chromewebstore.google.com/detail/exportthiscookie/dannllckdimllhkiplchkcaoheibealk), but does not mentioned that downloaded with it `cookies.txt` is not real json: it is necessary to trim `cookies = ` to make it valid json.
   But even with this I have no success:
   <details>
   
   ```
   Error loading cookie file: 'Gemini' object has no attribute 'session'
   Traceback (most recent call last):
     File "D:\AI\Gemini-API\test2.py", line 11, in <module>
       GeminiClient = Gemini(cookie_fp="cookies.json") # Or use cookie file path
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "D:\AI\Gemini-API\gemini\core.py", line 66, in __init__
       self.session = session or self._initialize_session()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "D:\AI\Gemini-API\gemini\core.py", line 94, in _initialize_session
       self._set_sid_and_nonce()
     File "D:\AI\Gemini-API\gemini\core.py", line 213, in _set_sid_and_nonce
       self._nonce = re.search(r'"SNlM0e":"(.*?)"', response.text).group(1)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   AttributeError: 'NoneType' object has no attribute 'group'
   ```
   </details>

2. `GeminiClient = Gemini(cookies=cookies)` (where cookies are `__Secure-1PSID`, `__Secure-1PSIDTS`)
   I get an output, but it is not very helpful:
   <details>

   ```
   {'metadata': ['c_409da1520e77ed5f', 'r_f3670ae69c52a4e1'], 'candidates': {'rcid': 'rc_594f1013ce897401', 'text': 'http://googleusercontent.com/card_content/0', 'web_images': [], 'generated_images': []}}
   ```
   </details>

3. `GeminiClient = Gemini(auto_cookies=True)` does not work:
   <details>

   ```
   Traceback (most recent call last):
     File "D:\AI\Gemini-API\test.py", line 3, in <module>
       GeminiClient = Gemini(auto_cookies=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
     File "D:\AI\Gemini-API\gemini\core.py", line 66, in __init__
       self.session = session or self._initialize_session()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "D:\AI\Gemini-API\gemini\core.py", line 92, in _initialize_session
       self._set_cookies_automatically()
     File "D:\AI\Gemini-API\gemini\core.py", line 141, in _set_cookies_automatically
       if len(getattr(self, "cookies", {})) > 5:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   TypeError: object of type 'NoneType' has no len()
   ```
   </details>

_Originally posted by @johnd0e in https://github.com/dsdanielpark/Gemini-API/issues/2#issuecomment-1981722593_

The issue is still relevant for v2.2.0

**Comment by dsdanielpark** [comment]
Thank you. I'm aware of this issue and others, needing to isolate errors and refactor, but detailed revisions are currently delayed due to the hiring process and other projects.

The most likely successful approach in your current situation is method 2, try rerunning the `generate_content` method without redeclaring the `Gemini` object. The first object of `generate_content` might be empty.


1. AttributeError: 'NoneType' object has no attribute 'group' 
   - The issue likely stems from invalid or expired cookies. Once exported cookie valuse, google expired or change cookie very fastly.

2. GeminiClient = Gemini(cookies=cookies) # where cookies are `__Secure-1PSID`, `__Secure-1PSIDTS` 
   - Refer to issue #14
   - Try rerunning the `generate_content` method without redeclaring the `Gemini` object.
   

3. Auto cookies
   - Auto-cookie update is not properly implemented yet; similar to point 1, cookies are received and then updated.
   - The package development was delayed because I aimed to automatically collect cookies from the browser perfectly from the start, ensuring error-free and comfortable use, but ultimately failed, causing a delay in the initial release.

I will try to make time to address this issue as soon as possible.

Also, I have marked `# To-Do` note in the source code to seek other contributors. 

We are waiting for many contributors. 
Additionally, I do not expect frequent updates or added features for the Gemini API, as there is an official Gemini API, unlike with Bard API.

**Comment by johnd0e** [comment]
@dsdanielpark 

Both `auto_cookie` and `cookies` failed: `ValueError: Failed to parse SNlM0e nonce value from the response`

If I make fresh login in incognito mode, then it does not fail, but response is not useful - #14

**Comment by dsdanielpark** [comment]
Try to use this and make sure you use 2.4.2.

Please pass the whole cookie manually.

https://github.com/dsdanielpark/Gemini-API/blob/main/scripts/sample.ipynb

**Comment by dsdanielpark** [comment]
Most of error fixed. If error persists, please reopen issue.

**Comment by johnd0e** [comment]
Sorry, still does not work, neither with `auto_cookies`, nor with manually set cookies.

And I have no problem using exactly same cookies set with another project - https://github.com/HanaokaYuzu/Gemini-API
