### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by RhancisDevs** [dsdanielpark/Gemini-API#26]
ImportError: cannot import name 'Gemini' from 'gemini' (/home/runner/Bard-ai/.pythonlibs/lib/python3.10/site-packages/gemini/__init__.py)

**Comment by dsdanielpark** [comment]
Could you possibly have installed a different package named gemini? Currently, in version 2.4.2, there is no import error. Therefore, I recommend running it in a virtual environment using conda or python venv.

1. You can check the version of the python-gemini-api you are currently using as follows:
    ```python
    import gemini
    print(gemini.__version__)
    ```

2. If you are using a gemini package with a different name, please set up a virtual environment and reinstall it as follows:
    ```python
    conda create -n gemini_venv python==3.9
    pip install python-gemini-api
    ```

3. If the problem persists, download the corresponding GitHub repository, place it where you intend to use it, and mount it. You can prevent conflicts by renaming the top-level folder to something other than gemini.

Thank you. 
This issue is unrelated to a package error and will be closed.
