### ISSUE TITLE
integration/compatibility with visual programming platforms

### ISSUE THREAD

**Issue by J-Fo-S** [dsdanielpark/Gemini-API#28]
I know this is an "unofficial" api, but I'm wondering if there are any plans, or how hard it would be, to integrate this api with some visual programming platform, something like flowise, langflow or chainforge. I know these platforms wouldn't officially support this, but the code is open-source so it is possible. Any thoughts on this?

**Comment by dsdanielpark** [comment]
Please be aware that this package may cease functioning at any time due to changes in Google's policies and interfaces. Given its instability, it is uncertain whether any pull requests for the packages listed will be accepted. Currently, I do not have plans to specifically use these packages as they are not in my current scope of work.

However, if needed, you can implement custom functionalities similar to the [Langchain custom sample script](https://github.com/dsdanielpark/Gemini-API/blob/main/scripts/langchain.ipynb), inheriting from the base class provided in each package. Should you choose to implement this, please include your script, and I will update the readme accordingly.
